package TYPO3Presets.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0b, conceptFqName)) {
      case 0:
        return new ConceptDescriptorBuilder("TYPO3Presets.structure.ExtensionRef_preset").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").references("Extension").create();
      case 1:
        return new ConceptDescriptorBuilder("TYPO3Presets.structure.Preset").super_("SoftwareSystems.structure.AbstractPreset").parents("SoftwareSystems.structure.AbstractPreset").references("Stock").children(new String[]{"AvailableFeatures", "AvailableVersions", "AvailableExtensions", "AvailablePurposes"}, new boolean[]{true, true, true, true}).alias("Preset", "").create();
      case 2:
        return new ConceptDescriptorBuilder("TYPO3Presets.structure.PresetRef").super_("SoftwareSystems.structure.AbstractPreset").parents("SoftwareSystems.structure.AbstractPreset").references("preset").alias("preset ref", "").create();
      case 3:
        return new ConceptDescriptorBuilder("TYPO3Presets.structure.VersionRef").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").references("version").create();
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }

  private static String[] stringSwitchCases_1htk8d_a0a0b = new String[]{"TYPO3Presets.structure.ExtensionRef_preset", "TYPO3Presets.structure.Preset", "TYPO3Presets.structure.PresetRef", "TYPO3Presets.structure.VersionRef"};
}
