package TYPO3Presets.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ExtensionRef_preset_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ExtensionRef_preset_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TYPO3Presets.structure.ExtensionRef_preset";
  }
}
