package TYPO3Presets.behavior;

/*Generated by MPS */

import SoftwareSystems.behavior.AbstractPreset_BehaviorDescriptor;

public class Preset_BehaviorDescriptor extends AbstractPreset_BehaviorDescriptor {
  public Preset_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TYPO3Presets.structure.Preset";
  }
}
