package TYPO3Presets.behavior;

/*Generated by MPS */


public class PresetRef_BehaviorDescriptor extends AbstractPreset_BehaviorDescriptor {
  public PresetRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TYPO3Presets.structure.PresetRef";
  }
}
