package TYPO3System.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Feature_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Feature_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TYPO3System.structure.Feature";
  }
}
