package TYPO3System.behavior;

/*Generated by MPS */


public class Role_BehaviorDescriptor extends AbstractRole_BehaviorDescriptor {
  public Role_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TYPO3System.structure.Role";
  }
}
