package TYPO3System.behavior;

/*Generated by MPS */


public class RoleRef_BehaviorDescriptor extends AbstractRole_BehaviorDescriptor {
  public RoleRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TYPO3System.structure.RoleRef";
  }
}
