package TYPO3System.behavior;

/*Generated by MPS */

import SoftwareSystems.behavior.SoftwareSystem_BehaviorDescriptor;

public class TYPO3System_BehaviorDescriptor extends SoftwareSystem_BehaviorDescriptor {
  public TYPO3System_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TYPO3System.structure.TYPO3System";
  }
}
