package UserLanguage.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.intentions.IntentionsManager;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("b0232009-1c88-477b-94e6-1f51d46fa70b(UserLanguage)"), PersistenceFacade.getInstance().createModelReference("r:6d84db45-bc17-45c2-9b15-37b64c8dae42(UserLanguage.intentions)"));
  }

  public void init() {
    IntentionsManager.getInstance().registerIntentionFactory(new RunRule_Intention());
  }
}
