package UserLanguage.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import UserLanguage.behavior.System_Behavior;
import jetbrains.mps.intentions.IntentionDescriptor;

public class RunRule_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public RunRule_Intention() {
  }

  public String getConcept() {
    return "UserLanguage.structure.System";
  }

  public String getPresentation() {
    return "RunRule";
  }

  public String getPersistentStateKey() {
    return "UserLanguage.intentions.RunRule_Intention";
  }

  public String getLanguageFqName() {
    return "UserLanguage";
  }

  public IntentionType getType() {
    return IntentionType.NORMAL;
  }

  public boolean isAvailableInChildNodes() {
    return true;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:6d84db45-bc17-45c2-9b15-37b64c8dae42(UserLanguage.intentions)", "8386501579414534845");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new RunRule_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Execute the Rule Run";
    }

    public void execute(final SNode node, final EditorContext editorContext) {
      System_Behavior.call_callExternal_1878540589877588861(node);
    }

    public IntentionDescriptor getDescriptor() {
      return RunRule_Intention.this;
    }
  }
}
