package TYPO3Stock.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {


  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ExtensionRef_stock_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new FeatureRef_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new PurposeRef_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new VersionRef_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    return Collections.<ConceptEditorComponent>emptyList();
  }



  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"TYPO3Stock.structure.ExtensionRef_stock", "TYPO3Stock.structure.FeatureRef", "TYPO3Stock.structure.PurposeRef", "TYPO3Stock.structure.VersionRef"};
}
