package UserLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Extensions_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Extensions_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "UserLanguage.structure.Extensions";
  }
}
