package UserLanguage.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import com.sample.DroolsTest;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

public class System_Behavior {
  public static void init(SNode thisNode) {
    System_Behavior.call_callExternal_1878540589877588861(thisNode);
  }

  public static void call_callExternal_1878540589877588861(SNode thisNode) {
    // <node> 
    // <node> 
    ClassLoader currentCCL = Thread.currentThread().getContextClassLoader();
    try {
      Thread.currentThread().setContextClassLoader(thisNode.getClass().getClassLoader());

      DroolsTest.runRule();

      if (LOG.isInfoEnabled()) {
        LOG.info("Yeah!");
      }

    } catch (Throwable e) {
      if (LOG.isEnabledFor(Level.ERROR)) {
        LOG.error("Err: ", e);
      }
    } finally {
      if (LOG.isInfoEnabled()) {
        LOG.info("End!");
      }
      Thread.currentThread().setContextClassLoader(currentCCL);
    }
  }

  protected static Logger LOG = LogManager.getLogger(System_Behavior.class);
}
