package UserLanguage.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class System_Behavior {
  public static void init(SNode thisNode) {
    System_Behavior.call_callExternal_1878540589877588861(thisNode);
  }

  public static void call_callExternal_1878540589877588861(SNode thisNode) {
    // <node> 
    // <node> 
    // <node> 
    // <node> 
    // <node> 
  }
}
