package PresetLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum System_Environment {
  a_Test_environment("a Test environment", "test"),
  a_Production_environment("a Production environment", "production"),
  a_Development_environment("a Development environment", "development");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<System_Environment> getConstants() {
    List<System_Environment> list = ListSequence.fromList(new LinkedList<System_Environment>());
    ListSequence.fromList(list).addElement(System_Environment.a_Test_environment);
    ListSequence.fromList(list).addElement(System_Environment.a_Production_environment);
    ListSequence.fromList(list).addElement(System_Environment.a_Development_environment);
    return list;
  }

  public static System_Environment getDefault() {
    return System_Environment.a_Development_environment;
  }

  public static System_Environment parseValue(String value) {
    if (value == null) {
      return System_Environment.getDefault();
    }
    if (value.equals(System_Environment.a_Test_environment.getValueAsString())) {
      return System_Environment.a_Test_environment;
    }
    if (value.equals(System_Environment.a_Production_environment.getValueAsString())) {
      return System_Environment.a_Production_environment;
    }
    if (value.equals(System_Environment.a_Development_environment.getValueAsString())) {
      return System_Environment.a_Development_environment;
    }
    return System_Environment.getDefault();
  }

  private String myValue;

  System_Environment(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
