package TYPO3SystemJSONGenerator.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;

public class TYPO3System_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    TYPO3System_JSON.typo3system(node, this);
  }

  public String getExtension(SNode node) {
    return "json";
  }

  @Override
  public String getFilename(SNode node) {
    return "System";
  }
}
