package TYPO3SystemJSONGenerator.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;

public class User_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {

  }
}
