package UserLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class System_Constraints extends BaseConstraintsDescriptor {
  public System_Constraints() {
    super("UserLanguage.structure.System");
  }
}
