package TYPO3Stock.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 0:
        return new Extension_BehaviorDescriptor();
      case 3:
        return new Stock_BehaviorDescriptor();
      case 1:
        return new Feature_BehaviorDescriptor();
      case 2:
        return new Purpose_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"TYPO3Stock.structure.Extension", "TYPO3Stock.structure.Feature", "TYPO3Stock.structure.Purpose", "TYPO3Stock.structure.Stock"};
}
