package TYPO3Stock.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ExtensionRef_stock_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ExtensionRef_stock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TYPO3Stock.structure.ExtensionRef_stock";
  }
}
