package TYPO3Stock.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class FeatureRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public FeatureRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TYPO3Stock.structure.FeatureRef";
  }
}
