package TYPO3Stock.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class PurposeRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PurposeRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TYPO3Stock.structure.PurposeRef";
  }
}
