package TYPO3Stock.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Stock_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Stock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TYPO3Stock.structure.Stock";
  }
}
