package TYPO3Stock.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class VersionRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public VersionRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TYPO3Stock.structure.VersionRef";
  }
}
